#debug: false
#logging:
#  level:
#    cn.edu.fjnu.towide: debug
logging:
  config: classpath:logback-boot.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/enjoy_meal?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin


#    url: jdbc:mysql://47.106.139.233:3306/yzb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8


#    url: jdbc:mysql://127.0.0.1:3306/yzb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8

#        username: root
#        password: 123456
#    url: jdbc:mysql://www.towide.cn:3306/fjnu_admissions_office?allowMultiQueries=true
#    username: fjnuadmissionsoffice
#    password: byqj301
#    initialize: true
#    init-db: true



#  redis:
#   database: 0
#    host: www.towide.cn
#    port: 6379
#    password: 
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#    timeout: 0



pagehelper:
  helper-dialect: mysql

mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:

  port: 8082
#  port: 446
#  ssl:
#   key-store: classpath:tomcat.keystore
#   key-password: 123456

email:
  # 用户名
  user: 
  # 密码
  password: 
  # 标题
  title: 无

mns:
  AccessKeyId: 
  AccessKeySecret: 
  accountEndpoint: 
  queueName: event-queue

wechat:
  app_id: 
  app_secret: 
  get_session_key_api: 


kdniao:
  ebusinessid: 1366398
  appkey: 
  requrl: 

